In [87]:
import pandas as pd
import numpy as np
import math
from scipy.stats import ttest_ind, mannwhitneyu, shapiro
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.stats import kstest, zscore

In [88]:
gen = pd.read_csv('/account001/mansi.chandra/clin_path/results_vae_corr_mod/predictions_decoded/test/samples/generated_samples_s5_929201_ControlGenerator_test.csv')
real = pd.read_csv('/account001/mansi.chandra/clin_path/repeat_test.csv')
threshold = pd.read_csv('/account001/mansi.chandra/clin_path/best_per_feature.csv')

In [89]:
#optimizing the prediction values to be consistent with real 

gen["TBIL(mg/dL)"] = pd.to_numeric(gen["TBIL(mg/dL)"], errors="coerce").round(2)
gen["RALB(g/dL)"] = pd.to_numeric(gen["RALB(g/dL)"], errors="coerce").round(2)
gen["AST(IU/L)"] = pd.to_numeric(gen["AST(IU/L)"], errors="coerce").round().astype(int)
gen["TP(g/dL)"] = pd.to_numeric(gen["TP(g/dL)"], errors="coerce").round(1)
gen["CRE(mg/dL)"] = pd.to_numeric(gen["CRE(mg/dL)"], errors="coerce").round(1)
gen["DBIL(mg/dL)"] = pd.to_numeric(gen["DBIL(mg/dL)"], errors="coerce").round(2)
gen["BUN(mg/dL)"] = pd.to_numeric(gen["BUN(mg/dL)"], errors="coerce").round().astype(int)
gen["K(meq/L)"] = pd.to_numeric(gen["K(meq/L)"], errors="coerce").round(2)
gen["GTP(IU/L)"] = pd.to_numeric(gen["GTP(IU/L)"], errors="coerce").round().astype(int)
gen["Ca(mg/dL)"] = pd.to_numeric(gen["Ca(mg/dL)"], errors="coerce").round(1)
gen["Cl(meq/L)"] = pd.to_numeric(gen["Cl(meq/L)"], errors="coerce").round(1)
gen["Na(meq/L)"] = pd.to_numeric(gen["Na(meq/L)"], errors="coerce").round(1)
gen["IP(mg/dL)"] = pd.to_numeric(gen["IP(mg/dL)"], errors="coerce").round(1)
gen["ALP(IU/L)"] = pd.to_numeric(gen["ALP(IU/L)"], errors="coerce").round().astype(int)
gen["ALT(IU/L)"] = pd.to_numeric(gen["ALT(IU/L)"], errors="coerce").round().astype(int)
gen["LDH(IU/L)"] = pd.to_numeric(gen["LDH(IU/L)"], errors="coerce").round().astype(int)
gen["RALB(g/dL)"] = pd.to_numeric(gen["RALB(g/dL)"], errors="coerce").round(1)

In [90]:
# 1) Which features to score? (columns 11 onward)
feature_cols = real.columns[11:]

results = []

# 2) Loop per (compound, time)
for (compound, time), grp in real.groupby(['COMPOUND_NAME','SACRIFICE_PERIOD']):
    # 2a) pull the control rows
    ctrl = grp[grp['DOSE_LEVEL']=='Control']
    if ctrl.shape[0] < 2:
        continue

    # 2b) precompute control means & SDs per feature
    ctrl_means = ctrl[feature_cols].mean()
    ctrl_sds   = ctrl[feature_cols].std(ddof=1)

    # 3) for each treatment dose
    for dose in ['High']:
        trt = grp[grp['DOSE_LEVEL']==dose]
        if trt.empty:
            continue

        # 4) compute z‑scores for each individual treatment sample
        for _, row in trt.iterrows():
            rec = {
                'compound':      compound,
                'time':          time,
                'dose':          dose,
                'INDIVIDUAL_ID': row['INDIVIDUAL_ID']
            }
            for f in feature_cols:
                μ = ctrl_means[f]
                σ = ctrl_sds[f]
                x = row[f]

                # cannot compute if SD is zero or missing
                if pd.isna(σ) or σ == 0:
                    rec[f'{f}_z'] = np.nan
                else:
                    rec[f'{f}_z'] = (x - μ) / σ

            results.append(rec)

# 5) Build the final DataFrame
results_df = pd.DataFrame(results)

In [91]:
# 1) Identify z-score columns
z_cols = [col for col in results_df.columns if col.endswith('_z')]
keys   = ['compound','time','dose']

# 2) Container
feature_counts = []

# 3) Per-feature (NA-aware) counting
for z in z_cols:
    s = results_df[z]

    # cell-level abnormal (strict > 2), keep NaN as NA (nullable boolean)
    abn = s.abs().gt(2)
    abn = abn.where(s.notna(), pd.NA).astype('boolean')

    # group to treatment-level: any True among non-NA; also track usable count
    grp = (
        pd.concat([results_df[keys], abn.rename('abn')], axis=1)
          .groupby(keys)['abn']
          .agg(valid_n=lambda x: x.notna().sum(),
               abn_any=lambda x: x.any(skipna=True))
          .reset_index()
    )

    # exclude treatments where this feature had no usable value
    grp = grp[grp['valid_n'] > 0]

    # counts
    abn_count  = int((grp['abn_any'] == True).sum())
    norm_count = int((grp['abn_any'] == False).sum())

    feature_counts.append({
        'feature':  z[:-2],   # strip '_z'
        'abnormal': abn_count,
        'normal':   norm_count
    })

# 4) Result table
feature_status_df = pd.DataFrame(feature_counts)

feature_status_df

           feature  abnormal  normal
0        ALP(IU/L)        64      46
1        TC(mg/dL)        66      44
2        TG(mg/dL)        68      42
3        PL(mg/dL)        68      42
4      TBIL(mg/dL)        70      39
5      DBIL(mg/dL)        38      32
6       GLC(mg/dL)        62      48
7       BUN(mg/dL)        71      39
8       CRE(mg/dL)        16      45
9        Na(meq/L)        47      61
10        K(meq/L)        60      50
11       Cl(meq/L)        50      59
12       Ca(mg/dL)        69      41
13       IP(mg/dL)        68      42
14        TP(g/dL)        77      33
15      RALB(g/dL)        79      30
16             A/G        54      42
17       AST(IU/L)        63      47
18       ALT(IU/L)        71      39
19       LDH(IU/L)        74      36
20       GTP(IU/L)        32      54
21   RBC(x10_4/ul)        83      27
22        Hb(g/dL)        80      30
23           Ht(%)        74      36
24         MCV(fL)        67      43
25         MCH(pg)        56      54
26         MCHC(%)        69      41
27          Ret(%)        88      22
28  Plat(x10_4/uL)        63      47
29   WBC(x10_2/uL)        63      47
30          Neu(%)        62      48
31          Eos(%)         6      55
32          Bas(%)         0      16
33         Mono(%)        60      49
34          Lym(%)        66      44
35           PT(s)        76      34
36         APTT(s)        75      35
37      Fbg(mg/dL)        81      29

In [92]:
# 1) Which features to score? (columns 11 onward)
feature_cols = real.columns[11:]

results_gen_z = []

# 2) Loop over each synthetic‐control block (compound, targetTime)
for (gen_cmpd, gen_time), gen_ctrl_group in gen.groupby(['COMPOUND_NAME','targetTime']):
    # need at least two control samples to compute an SD
    if gen_ctrl_group.shape[0] < 2:
        continue

    # 2a) compute control means & SDs for this compound/time
    ctrl_means = gen_ctrl_group[feature_cols].mean()
    ctrl_sds   = gen_ctrl_group[feature_cols].std(ddof=1)

    # 3) for each treatment dose (Low, Middle, High)
    for real_dose in ['High']:
        real_treat = real.loc[
            (real['COMPOUND_NAME']    == gen_cmpd) &
            (real['SACRIFICE_PERIOD'] == gen_time)   &
            (real['DOSE_LEVEL']       == real_dose)
        ]
        if real_treat.empty:
            continue

        # 4) compute z‑scores for each individual sample
        for _, sample in real_treat.iterrows():
            rec = {
                'compound':       gen_cmpd,
                'time':           gen_time,
                'dose':           real_dose,
                'INDIVIDUAL_ID':  sample['INDIVIDUAL_ID']
            }
            for feat in feature_cols:
                x     = sample[feat]
                mu    = ctrl_means[feat]
                sigma = ctrl_sds[feat]

                # guard against zero or missing sd
                if pd.isna(x) or pd.isna(mu) or pd.isna(sigma) or sigma == 0:
                    rec[f'{feat}_z'] = np.nan
                else:
                    rec[f'{feat}_z'] = (x - mu) / sigma

            results_gen_z.append(rec)

# 5) assemble into a DataFrame
results_gen_z_df = pd.DataFrame(results_gen_z)

In [93]:

best_thresh = threshold.set_index('feature')['best_threshold'].to_dict()

z_cols_gen = [c for c in results_gen_z_df.columns if c.endswith('_z')]
keys = ['compound','time','dose']

feature_counts_gen = []

for z in z_cols_gen:
    feat = z[:-2]
    thr  = best_thresh.get(feat, 2)

    # Skip if this feature isn't present on the REAL side
    if z not in results_df.columns:
        continue

    # --- GEN: cell-level abnormal (NA-aware)
    s_gen = results_gen_z_df[z]
    abn   = s_gen.abs().gt(thr)
    abn   = abn.where(s_gen.notna(), pd.NA).astype('boolean')

    grp_gen = (
        pd.concat([results_gen_z_df[keys], abn.rename('abn_gen')], axis=1)
          .groupby(keys)['abn_gen']
          .agg(valid_n_gen=lambda x: x.notna().sum(),
               abn_gen_any=lambda x: x.any(skipna=True))
          .reset_index()
    )

    # --- REAL: per-group valid counts for the same feature
    grp_real_valid = (
        results_df[keys + [z]]
        .groupby(keys, as_index=False)[z]
        .count()
        .rename(columns={z: 'valid_n_real'})
    )

    # --- Intersect validity: keep only groups valid on BOTH sides
    merged = grp_gen.merge(grp_real_valid, on=keys, how='left')
    merged['valid_n_real'] = merged['valid_n_real'].fillna(0).astype(int)
    eligible = merged[(merged['valid_n_real'] > 0) & (merged['valid_n_gen'] > 0)]

    # Counts among eligible groups
    abn_count  = int((eligible['abn_gen_any'] == True).sum())
    norm_count = int((eligible['abn_gen_any'] == False).sum())

    feature_counts_gen.append({
        'feature':   feat,
        'threshold': thr,
        'abnormal':  abn_count,
        'normal':    norm_count,
    })

feature_status_gen_df = pd.DataFrame(feature_counts_gen)

feature_status_gen_df

           feature  threshold  abnormal  normal
0        ALP(IU/L)          6        50      60
1        TC(mg/dL)          3        77      33
2        TG(mg/dL)          3        77      33
3        PL(mg/dL)          4        69      41
4      TBIL(mg/dL)          2        70      39
5      DBIL(mg/dL)          2        46      24
6       GLC(mg/dL)          3        86      24
7       BUN(mg/dL)          3       103       7
8       CRE(mg/dL)          9         4      57
9        Na(meq/L)          5        45      63
10        K(meq/L)          3        74      36
11       Cl(meq/L)          3        83      26
12       Ca(mg/dL)          5        57      53
13       IP(mg/dL)          4        63      47
14        TP(g/dL)          3        90      20
15      RALB(g/dL)          4        48      61
16             A/G          3        58      38
17       AST(IU/L)          6        59      51
18       ALT(IU/L)          4        97      13
19       LDH(IU/L)          4        74      36
20       GTP(IU/L)          4        15      71
21   RBC(x10_4/ul)          4        77      33
22        Hb(g/dL)          2       108       2
23           Ht(%)          4        90      20
24         MCV(fL)          6        62      48
25         MCH(pg)          5        85      25
26         MCHC(%)          5        79      31
27          Ret(%)          1       107       3
28  Plat(x10_4/uL)          4        67      43
29   WBC(x10_2/uL)          3        87      23
30          Neu(%)          6        74      36
31          Eos(%)         20        10      51
32          Bas(%)         18         0      16
33         Mono(%)          5        75      34
34          Lym(%)          5        91      19
35           PT(s)          1       109       1
36         APTT(s)          6        65      45
37      Fbg(mg/dL)          3        93      17

In [94]:
# keys shared by both frames
keys = ['compound','time','dose']

# ── 1) REAL flags (NA-aware; unchanged) ──
real_chunks = []
for z in [c for c in results_df.columns if c.endswith('_z')]:
    feat = z[:-2]
    s = results_df[z]

    abn = s.abs().gt(2)
    abn = abn.where(s.notna(), pd.NA).astype('boolean')

    grp = (
        pd.concat([results_df[keys], abn.rename('abn_real')], axis=1)
          .groupby(keys)['abn_real']
          .agg(valid_n_real=lambda x: x.notna().sum(),
               abn_real_any=lambda x: x.any(skipna=True))
          .reset_index()
    )
    # only keep groups where REAL had ≥1 usable value for this feature
    grp = grp[grp['valid_n_real'] > 0]
    grp['feature'] = feat
    real_chunks.append(grp)

real_flags_df = pd.concat(real_chunks, ignore_index=True)

# ── 2) GEN flags (NA-aware; aligned to REAL validity) ──
gen_chunks = []
for z in [c for c in results_gen_z_df.columns if c.endswith('_z')]:
    feat = z[:-2]
    thr  = best_thresh.get(feat, 2)

    s = results_gen_z_df[z]
    abn = s.abs().gt(thr)
    abn = abn.where(s.notna(), pd.NA).astype('boolean')

    grp = (
        pd.concat([results_gen_z_df[keys], abn.rename('abn_gen')], axis=1)
          .groupby(keys)['abn_gen']
          .agg(valid_n_gen=lambda x: x.notna().sum(),
               abn_gen_any=lambda x: x.any(skipna=True))
          .reset_index()
    )
    # DO NOT drop gen groups just because gen had all-NaN;
    # instead mark abn_gen_any as <NA> when valid_n_gen == 0
    grp.loc[grp['valid_n_gen'] == 0, 'abn_gen_any'] = pd.NA
    grp['abn_gen_any'] = grp['abn_gen_any'].astype('boolean')

    grp['feature']   = feat
    grp['threshold'] = thr
    gen_chunks.append(grp)

gen_flags_df = pd.concat(gen_chunks, ignore_index=True)

# ── 3) Merge, keeping rows where REAL had ≥1 valid sample.
#     (GEN may be <NA>; those rows won’t contribute to TP/TN/FP/FN unless you tally NA mismatches separately.)
merged_flags = (
    real_flags_df.merge(gen_flags_df, on=keys+['feature'], how='inner')
                 .query('valid_n_real > 0')  # <- ONLY real validity enforced
                 # (optional) if you want to also require gen validity, add: and valid_n_gen > 0
)

# ── 4) Confusion per feature (nullable-boolean safe) ──
def as_bool(series):
    return series == True, series == False  # NA becomes neither mask

# ── 4) Confusion per feature (treat gen NA as False) ──
confusion = []
for feat, grp in merged_flags.groupby('feature'):
    grp2 = grp.copy()
    # fill NA on generated side with False
    grp2['abn_gen_any_filled'] = grp2['abn_gen_any'].fillna(False)

    r = grp2['abn_real_any'].astype(bool)
    g = grp2['abn_gen_any_filled'].astype(bool)

    TP = int(( r &  g).sum())
    TN = int((~r & ~g).sum())
    FP = int((~r &  g).sum())
    FN = int(( r & ~g).sum())

    # optional: how many gen NAs were filled for this feature
    na_filled = int(grp2['abn_gen_any'].isna().sum())

    confusion.append({
        'feature': feat,
        'TP': TP, 'TN': TN, 'FP': FP, 'FN': FN,
        'na_filled_gen': na_filled  # optional column
    })

confusion_df = pd.DataFrame(confusion)

In [95]:
# assume confusion_df has columns ['feature','TP','TN','FP','FN']

# 1) Compute total cases per feature
confusion_df['total'] = (
    confusion_df['TP'] +
    confusion_df['TN'] +
    confusion_df['FP'] +
    confusion_df['FN']
)

# 2) Compute accuracy = (TP + TN) / total
confusion_df['accuracy'] = (
    (confusion_df['TP'] + confusion_df['TN']) /
    confusion_df['total']
)

# 3) (Optional) drop the 'total' column if you don’t need it
confusion_df = confusion_df.drop(columns=['total'])

In [96]:
confusion_df

           feature  TP  TN  FP  FN  na_filled_gen  accuracy
0              A/G  41  25  17  13              0  0.687500
1        ALP(IU/L)  40  36  10  24              0  0.690909
2        ALT(IU/L)  70  12  27   1              0  0.745455
3          APTT(s)  50  20  15  25              0  0.636364
4        AST(IU/L)  42  30  17  21              0  0.654545
5       BUN(mg/dL)  69   5  34   2              0  0.672727
6           Bas(%)   0  16   0   0              0  1.000000
7       CRE(mg/dL)   3  44   1  13              0  0.770492
8        Ca(mg/dL)  43  27  14  26              0  0.636364
9        Cl(meq/L)  39  15  44  11              0  0.495413
10     DBIL(mg/dL)  31  17  15   7              0  0.685714
11          Eos(%)   2  47   8   4              0  0.803279
12      Fbg(mg/dL)  73   9  20   8              0  0.745455
13      GLC(mg/dL)  58  20  28   4              0  0.709091
14       GTP(IU/L)  12  51   3  20              0  0.732558
15        Hb(g/dL)  78   0  30   2              0  0.709091
16           Ht(%)  64  10  26  10              0  0.672727
17       IP(mg/dL)  44  23  19  24              0  0.609091
18        K(meq/L)  48  24  26  12              0  0.654545
19       LDH(IU/L)  59  21  15  15              0  0.727273
20          Lym(%)  61  14  30   5              0  0.681818
21         MCH(pg)  49  18  36   7              0  0.609091
22         MCHC(%)  53  15  26  16              0  0.618182
23         MCV(fL)  45  26  17  22              0  0.645455
24         Mono(%)  50  24  25  10              0  0.678899
25       Na(meq/L)  28  44  17  19              0  0.666667
26          Neu(%)  49  23  25  13              0  0.654545
27       PL(mg/dL)  52  25  17  16              0  0.700000
28           PT(s)  76   1  33   0              0  0.700000
29  Plat(x10_4/uL)  43  23  24  20              0  0.600000
30      RALB(g/dL)  39  21   9  40              0  0.550459
31   RBC(x10_4/ul)  67  17  10  16              0  0.763636
32          Ret(%)  87   2  20   1              0  0.809091
33     TBIL(mg/dL)  52  21  18  18              0  0.669725
34       TC(mg/dL)  56  23  21  10              0  0.718182
35       TG(mg/dL)  54  19  23  14              0  0.663636
36        TP(g/dL)  65   8  25  12              0  0.663636
37   WBC(x10_2/uL)  55  15  32   8              0  0.636364

In [97]:
# --- Params ---
feat = "Cl(meq/L)"
thr  = best_thresh.get(feat, 2)

keys = ['compound','time','dose']
zcol_real = f'{feat}_z'
zcol_gen  = f'{feat}_z'

def max_abs_safe(s: pd.Series):
    s = s.dropna()
    return np.nan if s.empty else float(np.abs(s).max())

# --- Real: per-treatment z-aggregates + abnormal flag (|z|>2) ---
real_agg = (
    results_df[keys + [zcol_real]]
    .groupby(keys, as_index=False)
    .agg(
        z_real_list    = (zcol_real, lambda s: s.dropna().tolist()),
        max_abs_z_real = (zcol_real, max_abs_safe),
        mean_z_real    = (zcol_real, 'mean'),
        n_real         = (zcol_real, 'count')
    )
)
real_agg['abn_real'] = real_agg['max_abs_z_real'].abs() > 2

# --- Generated: per-treatment z-aggregates + abnormal flag (|z|>thr) ---
gen_agg = (
    results_gen_z_df[keys + [zcol_gen]]
    .groupby(keys, as_index=False)
    .agg(
        z_gen_list    = (zcol_gen, lambda s: s.dropna().tolist()),
        max_abs_z_gen = (zcol_gen, max_abs_safe),
        mean_z_gen    = (zcol_gen, 'mean'),
        n_gen         = (zcol_gen, 'count')
    )
)
gen_agg['abn_gen'] = gen_agg['max_abs_z_gen'].abs() > thr

# --- Merge real/gen z-aggregates ---
cmp = real_agg.merge(gen_agg, on=keys, how='inner')

# ==========================================================
# Add CONTROL mean/variance for THIS feature per (compound, time)
# (no GROUPS needed; attach to every (compound,time,dose) after merge)
#   - From real (DOSE_LEVEL == 'Control'): ctrl_mean_real, ctrl_var_real
#   - From gen  (synthetic controls at targetTime): ctrl_mean_gen,  ctrl_var_gen
# ==========================================================

# From REAL data: compute control stats per (compound,time)
# Requires a DataFrame `real` with columns: COMPOUND_NAME, SACRIFICE_PERIOD, DOSE_LEVEL, and feature columns
_real_ctrl = (
    real.loc[real['DOSE_LEVEL'] == 'Control', ['COMPOUND_NAME', 'SACRIFICE_PERIOD', feat]]
        .groupby(['COMPOUND_NAME', 'SACRIFICE_PERIOD'])
        .agg(
            ctrl_mean_real = (feat, 'mean'),
            ctrl_var_real  = (feat, lambda s: s.std(ddof=1) if s.size > 1 else np.nan)
        )
        .reset_index()
        .rename(columns={'COMPOUND_NAME': 'compound', 'SACRIFICE_PERIOD': 'time'})
)

# From GENERATED data: compute synthetic-control stats per (compound,time)
# Requires a DataFrame `gen` with columns: COMPOUND_NAME, targetTime, and feature columns
_gen_ctrl = (
    gen[['COMPOUND_NAME', 'targetTime', feat]]
        .groupby(['COMPOUND_NAME', 'targetTime'])
        .agg(
            ctrl_mean_gen = (feat, 'mean'),
            ctrl_var_gen  = (feat, lambda s: s.std(ddof=1) if s.size > 1 else np.nan)
        )
        .reset_index()
        .rename(columns={'COMPOUND_NAME': 'compound', 'targetTime': 'time'})
)

# Merge control stats onto cmp (replicates across each dose at that (compound,time))
cmp = (
    cmp.merge(_real_ctrl, on=['compound','time'], how='left')
       .merge(_gen_ctrl,  on=['compound','time'], how='left')
)

# --- Find treatment-level mismatches ---
mismatches = cmp.loc[cmp['abn_real'] != cmp['abn_gen']].copy()

mismatches['threshold_gen'] = thr
mismatches['error_type'] = np.select(
    [
        (~mismatches['abn_real']) & (mismatches['abn_gen']),  # FP
        (mismatches['abn_real'])  & (~mismatches['abn_gen'])  # FN
    ],
    ['FP', 'FN'],
    default='(other)'
)

# Include the new control mean/var columns
mismatches = mismatches[
    keys + [
        'abn_real','abn_gen','error_type','threshold_gen',
        'n_real','n_gen',
        'max_abs_z_real','max_abs_z_gen',
        'mean_z_real','mean_z_gen',
        'z_real_list','z_gen_list',
        'ctrl_mean_real','ctrl_var_real',
        'ctrl_mean_gen','ctrl_var_gen'
    ]
].sort_values(keys)

mismatches  # <- disagreements + control mean/var for the given feature, per (compound,time,dose)

,compound,time,dose,abn_real,abn_gen,error_type,threshold_gen,n_real,n_gen,max_abs_z_real,max_abs_z_gen,mean_z_real,mean_z_gen,z_real_list,z_gen_list,ctrl_mean_real,ctrl_var_real,ctrl_mean_gen,ctrl_var_gen
0,amiodarone,15 day,High,False,True,FP,3,5,5,0.923133,4.124257,-2.637522e-01,-3.298746e+00,"[-0.9231326627541057, 0.39562828403746847, 0.3...","[-4.124257498216263, -2.4732336798750834, -2.4...",101.40,1.516575,104.996000,1.211370
1,amiodarone,29 day,High,False,True,FP,3,4,4,1.258396,5.433867,-4.256341e-01,-3.329529e+00,"[0.22206996305927948, -1.258396457335931, -0.1...","[-1.6928224532479499, -5.4338665488235245, -2....",102.40,2.701851,104.810000,1.069220
2,amiodarone,4 day,High,False,True,FP,3,5,5,1.129368,4.060075,4.343722e-01,-6.641014e-01,"[-0.6081211398682996, 0.2606233456578392, 0.26...","[-4.060074621099688, -1.2300969576937963, -1.2...",103.40,2.302173,104.869333,0.706719
3,amiodarone,8 day,High,False,True,FP,3,5,5,0.526235,4.037039,-8.770580e-02,-2.896633e+00,"[-0.08770580193070417, -0.08770580193070417, 0...","[-2.896632794569062, -2.896632794569062, -1.75...",103.20,2.280351,105.540000,0.876880
4,amitriptyline,15 day,High,False,True,FP,3,5,5,1.224745,4.239718,-8.164966e-01,-3.357179e+00,"[-0.8164965809277261, -1.2247448713915892, -0....","[-3.3571786436227615, -4.239717719233368, -3.3...",106.00,2.449490,107.804000,1.133094
5,amitriptyline,29 day,High,False,True,FP,3,3,3,1.643168,4.632758,-1.034587e+00,-3.763698e+00,"[-1.6431676725154958, -1.6431676725154958, 0.1...","[-4.632757649490626, -4.632757649490626, -2.02...",104.80,1.095445,106.553846,0.767112
12,benzbromarone,15 day,High,False,True,FP,3,5,5,1.592607,4.417492,-3.781009e-01,2.679191e+00,"[-1.5926068113410878, -0.3895585006158013, -0....","[0.4856205659345968, 2.6584966777158687, 2.761...",108.08,1.745566,104.830667,0.966461
13,benzbromarone,29 day,High,False,True,FP,3,4,4,1.917933,5.427240,1.163907e+00,4.071919e+00,"[0.2938769068226259, 1.917933497158216, 1.3765...","[2.508087878138171, 5.427240040341782, 4.45418...",106.72,1.293058,105.295714,0.719387
15,benzbromarone,8 day,High,False,True,FP,3,4,4,0.639356,4.866416,2.187269e-01,4.061860e+00,"[0.6393556558250804, -0.4542790186125678, 0.05...","[4.866416019538509, 2.774569738111953, 3.74003...",106.54,1.188697,104.275714,0.621461
17,benziodarone,29 day,High,False,True,FP,3,5,5,1.582513,3.710391,5.275044e-01,1.797818e+00,"[0.26375218935831857, 0.9231326627541057, 1.58...","[1.3196750599918146, 2.5150329041872994, 3.710...",105.60,1.516575,104.896000,0.836570
18,benziodarone,4 day,High,False,True,FP,3,5,5,1.157383,6.192572,9.644856e-02,1.709139e+00,"[-0.2893456933022446, -0.7715885154726567, 1.1...","[0.07879973228339966, -1.9591243784954322, 6.1...",104.60,2.073644,103.961333,0.490695
20,bromobenzene,15 day,High,False,True,FP,3,5,5,0.664364,3.984547,-8.304548e-02,-2.484986e+00,"[-0.6643638388299173, 0.16609095970748228, 0.1...","[-3.984546894376877, -1.8423173812710285, -1.8...",106.60,2.408319,108.720000,0.933607
21,bromobenzene,29 day,High,True,False,FN,3,5,5,4.082483,2.920435,2.286190e+00,-3.250420e-01,"[1.6329931618554523, 0.0, 4.08248290463863, 1....","[-1.0665827502715604, -2.920434575772535, 1.71...",104.00,1.224745,107.150667,1.078835
22,bromobenzene,4 day,High,False,True,FP,3,5,5,1.937316,5.640158,1.332268e-15,-2.713309e+00,"[-0.830278087225995, -0.36901248321155267, 0.5...","[-4.5948543055152085, -3.549551083591048, -1.4...",104.80,2.167948,107.395714,0.956660
24,carboplatin,15 day,High,True,False,FN,3,5,5,3.157409,1.019476,2.631174e+00,-9.681145e-15,"[2.2803508501982708, 2.2803508501982708, 3.157...","[-0.679650414693084, -0.679650414693084, 1.019...",104.40,1.140175,107.400000,0.588538
26,carboplatin,4 day,High,False,True,FP,3,5,5,1.227881,7.458716,-3.508232e-01,-4.775725e+00,"[-1.2278812270298458, -1.2278812270298458, 0.5...","[-7.458716468794554, -7.458716468794554, -2.09...",105.40,1.140175,106.780000,0.372718
28,cephalothin,15 day,High,True,False,FN,3,5,5,5.142956,2.434068,2.012461e+00,-4.575857e-01,"[-0.4472135954999643, 2.90688837074972, 0.6708...","[-2.434068449272977, 0.2611352962310575, -1.53...",104.40,0.894427,106.709333,1.113088
30,cephalothin,4 day,High,False,True,FP,3,5,5,1.788854,11.812832,6.708204e-01,-2.872747e+00,"[-1.5652475842498592, 0.6708203932499306, 0.67...","[-11.812831973407102, -2.8727472306670805, -2....",105.40,0.894427,106.642667,0.223712
31,cephalothin,8 day,High,False,True,FP,3,5,5,1.414214,3.949385,4.242641e-01,1.383262e+00,"[0.7071067811865475, 0.0, 0.0, 0.0, 1.41421356...","[2.116440119811233, 0.28349544330033416, 0.283...",107.00,1.414214,106.845333,0.545570
32,chlormadinone,15 day,High,True,False,FN,3,5,5,2.828427,2.180578,8.485281e-01,1.058222e+00,"[1.414213562373095, 2.82842712474619, 1.414213...","[1.3788949917588806, 2.1805781265024162, 1.378...",107.00,0.707107,106.280000,1.247376
34,chlormadinone,4 day,High,False,True,FP,3,5,5,1.095445,8.474914,-3.651484e-01,-4.526972e+00,"[0.12171612389003865, -0.48686449556014594, -0...","[-1.8950117430246904, -5.184962685776008, -5.1...",105.80,1.643168,106.576000,0.303956
35,chlormadinone,8 day,High,False,True,FP,3,5,5,1.663601,5.352142,5.198752e-01,2.297323e-01,"[0.10397504898200874, 0.10397504898200874, -0....","[-1.632962216139218, -1.632962216139218, -3.96...",105.80,1.923538,106.701333,0.429485
37,chlorpromazine,29 day,High,False,True,FP,3,4,4,1.431253,3.213887,-6.055301e-01,-1.653747e+00,"[-0.8807710121010853, -1.4312528946642658, -0....","[-2.1737938732538487, -3.213886635576255, -1.1...",105.60,1.816590,106.090000,0.961453
40,cisplatin,15 day,High,False,True,FP,3,5,5,1.414214,5.510318,5.656854e-01,-1.025175e+00,"[-1.414213562373095, 1.414213562373095, 0.7071...","[-5.510318148948857, 0.8970285358753995, -0.70...",106.00,1.414214,107.440000,0.624283
42,cisplatin,4 day,High,False,True,FP,3,5,5,1.476050,8.847224,-3.690125e-01,-3.218025e+00,"[1.2915436912404379, -0.5535187248173323, -0.5...","[5.225772887517799, -4.156225115207178, -4.156...",106.20,2.167948,106.772000,0.426348
44,cyclosporine A,15 day,High,True,False,FN,3,5,5,2.373770,2.166540,1.318761e+00,1.558301e-01,"[0.39562828403746847, 1.0550087574332556, 2.37...","[-1.6035415636742538, -0.3468475482555699, 2.1...",105.40,1.516575,107.276000,0.795739
46,cyclosporine A,4 day,High,False,True,FP,3,5,5,1.687323,9.501478,-1.533930e-01,-2.750072e+00,"[-0.9203579866168468, -0.15339299776947626, 1....","[-6.125774956114972, -2.7500723719223, 4.00133...",106.20,1.303840,106.814667,0.296235
47,cyclosporine A,8 day,High,False,True,FP,3,5,5,1.643168,5.661776,-2.575717e-15,-3.536839e+00,"[-1.0954451150103348, 0.730296743340219, -0.18...","[-5.661775973339994, -2.1202146889321574, -3.8...",105.20,1.095445,107.197333,0.564723
51,diltiazem,8 day,High,True,False,FN,3,5,5,2.104939,2.383310,-7.016464e-01,-1.145762e+00,"[-2.104939246336875, -0.35082320772281667, -0....","[-2.383309582069539, -0.8363756257284275, -0.8...",106.40,1.140175,107.081333,1.292880
54,enalapril,4 day,High,False,True,FP,3,5,5,1.897367,3.391504,-6.324555e-01,2.159385e-01,"[0.6324555320336759, -1.8973665961010275, -1.2...","[3.391504053739549, -2.9596271330386457, -1.37...",105.00,1.581139,103.864000,0.629809
56,gemfibrozil,15 day,High,False,True,FP,3,5,5,0.949289,3.240687,-5.424508e-01,-2.200895e+00,"[-0.2712254014483232, -0.6102571532587283, -0....","[-1.5076993956132163, -2.374193301138056, -2.3...",105.80,2.949576,106.740000,1.154076
58,gemfibrozil,4 day,High,False,True,FP,3,5,5,1.095445,3.620830,2.575717e-15,-2.278954e+00,"[0.18257418583505797, -0.730296743340219, 1.09...","[-1.9434845253996174, -3.620830203247375, -0.2...",104.80,1.095445,106.158667,0.596180
59,gemfibrozil,8 day,High,False,True,FP,3,5,5,1.332420,4.744568,-6.662099e-01,-2.719539e+00,"[-1.3324197783556875, -0.9623031732568847, 0.5...","[-4.744567722775994, -3.6195516645774486, 0.88...",105.60,2.701851,106.217333,0.888876
61,imipramine,29 day,High,True,False,FN,3,4,4,2.151411,2.720652,-5.976143e-02,-5.704592e-01,"[1.4342743312012758, -2.151411496801905, -0.95...","[0.9653925535687792, -2.7206517418755554, -1.4...",105.80,0.836660,106.214286,0.813881
65,iproniazid,29 day,High,False,True,FP,3,5,5,1.009050,5.749722,2.162250e-01,-4.958615e-01,"[1.009049958219025, 0.6486749731408015, -0.432...","[5.749722428783357, 2.9108206370864886, -5.605...",105.20,2.774887,105.974667,0.352249
71,ketoconazole,8 day,High,False,True,FP,3,5,5,1.333772,3.730540,6.155870e-01,1.401725e+00,"[0.8207826816681204, 0.8207826816681204, 1.333...","[2.0671008114581606, 2.0671008114581606, 3.730...",106.40,1.949359,106.757333,0.601164
72,lomustine,15 day,High,False,True,FP,3,5,5,1.887760,3.403223,-6.741999e-01,7.061443e-01,"[-1.887759614897076, -0.5393598899705918, -0.5...","[-1.5005565535589256, 0.9513332398380042, 0.95...",106.80,1.483240,105.224000,0.815697
74,lomustine,4 day,High,False,True,FP,3,5,5,1.253831,4.930008,1.928971e-01,8.349636e-01,"[-0.1928971288681676, 0.7715885154726567, 1.25...","[-0.6541434765745238, 3.068624276288629, 4.930...",104.40,2.073644,104.351429,0.537235
75,lomustine,8 day,High,False,True,FP,3,5,5,0.878310,5.644748,1.951800e-01,2.716292e+00,"[-0.5855400437691214, 0.8783100656536786, 0.39...","[-0.6305145037079227, 5.644748329404064, 3.552...",105.20,2.049390,104.301429,0.478068
78,lornoxicam,8 day,High,True,False,FN,3,3,3,2.454288,2.424515,1.942978e+00,1.611968e+00,"[2.454287964311588, 2.454287964311588, 0.92035...","[2.4245151417357294, 2.4245151417357294, -0.01...",102.80,1.303840,104.010769,0.820465
80,mefenamic acid,29 day,High,True,False,FN,3,4,4,2.921187,1.036575,1.551881e+00,4.278480e-01,"[2.921186973360876, 2.921186973360876, 1.09544...","[1.0365747636985614, 1.0365747636985614, 0.224...",103.40,0.547723,103.722857,1.232080
81,mefenamic acid,4 day,High,False,True,FP,3,5,5,1.643168,3.828480,1.825742e-01,-1.893042e+00,"[0.730296743340219, -0.18257418583505797, 1.64...","[-1.0635691369973421, -2.4460246876870984, 0.3...",103.20,1.095445,104.769333,0.723351
82,mefenamic acid,8 day,High,False,True,FP,3,5,5,1.788854,3.309925,2.236068e-01,-1.600106e+00,"[-0.4472135954999643, 1.7888543819998255, 1.78...","[-2.2412876774257335, -0.10401398630139033, -0...",103.40,0.894427,105.097333,0.935772
84,meloxicam,4 day,High,False,True,FP,3,5,5,1.253831,3.210848,-2.893457e-01,-8.063189e-01,"[0.1928971288681676, -0.7715885154726567, 0.19...","[0.3959458511768862, -2.008583609411458, 0.395...",103.60,2.073644,103.670667,0.831764
86,phenobarbital,15 day,High,False,True,FP,3,5,5,1.253831,3.058382,8.680371e-01,2.032653e+00,"[1.2538313376430688, 0.2893456933022446, 1.253...","[3.0583823376536574, 0.4940595279943604, 3.058...",105.40,2.073644,105.614667,0.779933
87,phenobarbital,29 day,High,False,True,FP,3,5,5,1.639626,9.160607,-9.644856e-02,3.150837e+00,"[-1.1573827732089919, 0.7715885154726567, 0.28...","[-1.5711256089402135, 7.014260232262981, 4.867...",106.40,2.073644,104.732000,0.465908
93,promethazine,8 day,High,False,True,FP,3,5,5,1.788854,6.727828,2.236068e-01,-3.437042e+00,"[1.5652475842498592, 0.4472135954999643, 1.565...","[-1.2431855808515668, -3.071399670339147, -1.2...",104.60,0.894427,106.680000,0.546982
95,rosiglitazone maleate,29 day,High,False,True,FP,3,5,5,1.632993,7.085909,0.000000e+00,1.367919e+00,"[0.0, 1.6329931618554523, 0.0, 0.0, -1.6329931...","[1.3679190728981232, 7.085908766684582, 1.3679...",105.00,1.224745,104.521538,0.349773
96,rosiglitazone maleate,4 day,High,False,True,FP,3,5,5,1.887760,5.142483,1.348400e+00,3.769934e+00,"[1.213559752433834, 1.887759614897076, 0.53935...","[3.4267970147053575, 5.142483103509779, 1.7111...",104.20,1.483240,104.002667,0.582857
98,thioacetamide,15 day,High,True,False,FN,3,5,5,4.242641,1.053554,2.828427e+00,-7.924386e-02,"[1.414213562373095, 4.242640687119285, 2.82842...","[-1.0535535618963774, 0.8950658497492036, -0.0...",103.00,0.707107,105.081333,1.026368
99,thioacetamide,29 day,High,True,False,FN,3,5,5,3.535534,2.835933,2.121320e+00,6.145756e-01,"[2.1213203435596424, 3.5355339059327373, 1.414...","[0.6145756204912518, 2.8359332849174868, -0.49...",103.00,1.414214,105.446667,0.900350
104,thioridazine,4 day,High,False,True,FP,3,5,5,1.153200,4.906991,-3.603750e-01,-1.363650e+00,"[-1.1531999522503167, -0.07207499701564575, -0...","[-4.906991290730396, -0.07516179219937179, -1....",104.20,2.774887,104.046667,0.620883
105,thioridazine,8 day,High,False,True,FP,3,5,5,1.827815,8.266788,-4.700097e-01,3.414783e+00,"[1.8278153875348273, -0.26111648393354675, -1....","[8.266787879883735, 3.8558739377492737, 1.6504...",106.25,0.957427,104.251667,0.453421
107,triazolam,29 day,High,False,True,FP,3,5,5,0.935775,3.945941,-3.119251e-01,-2.306353e+00,"[-0.935775440838064, 0.10397504898200875, -0.9...","[-3.9459411901244414, -1.2132949365756507, -3....",105.80,1.923538,106.888000,0.731891
108,triazolam,4 day,High,False,True,FP,3,5,5,1.704026,4.639998,-1.217161e+00,-3.883682e+00,"[-1.7040257344605152, -1.7040257344605152, -1....","[-4.639998435691177, -4.639998435691177, -4.63...",104.80,1.643168,106.908000,1.057759

In [98]:

# --- Setup
keys = ['compound','time','dose']
dbil_feat = "Cl(meq/L)"
zcol = f"{dbil_feat}_z"

# (Optional but recommended) normalize key dtypes/whitespace
for df in (results_df, results_gen_z_df):
    for k in keys:
        df[k] = df[k].astype(str).str.strip()

# --- Per-group valid counts (non-NaN) for DBIL_z
real_valid = (
    results_df[keys + [zcol]]
      .groupby(keys, as_index=False)[zcol].count()
      .rename(columns={zcol: 'valid_n_real'})
)

gen_valid = (
    results_gen_z_df[keys + [zcol]]
      .groupby(keys, as_index=False)[zcol].count()
      .rename(columns={zcol: 'valid_n_gen'})
)

# --- Also capture total generated rows per group (regardless of NaN)
gen_total = (
    results_gen_z_df[keys]
      .groupby(keys, as_index=False)
      .size()
      .rename(columns={'size':'gen_group_size'})
)

# --- Merge side-by-side
cmp = (
    real_valid.merge(gen_valid, on=keys, how='left')
              .merge(gen_total, on=keys, how='left')
)

# Fill missing gen columns with 0 -> means group absent in gen
cmp['valid_n_gen']   = cmp['valid_n_gen'].fillna(0).astype(int)
cmp['gen_group_size'] = cmp['gen_group_size'].fillna(0).astype(int)
cmp['valid_n_real']   = cmp['valid_n_real'].astype(int)

# --- Diagnose discrepancies where REAL had data but GEN did not
dbil_diff = cmp.query('valid_n_real > 0 and valid_n_gen == 0').copy()
dbil_diff['reason'] = np.where(
    dbil_diff['gen_group_size'] == 0,
    'missing_in_generated',      # no rows for this (compound,time,dose) in gen
    'all_NaN_in_generated'       # rows exist, but DBIL_z all NaN
)

# --- Quick tallies
n_real_groups = (cmp['valid_n_real'] > 0).sum()
n_gen_groups  = ((cmp['valid_n_real'] > 0) & (cmp['valid_n_gen'] > 0)).sum()
summary = {
    'real_groups_with_DBIL': int(n_real_groups),
    'gen_groups_eligible'  : int(n_gen_groups),
    'hard_na_or_missing'   : int(len(dbil_diff)),
    'by_reason'            : dbil_diff['reason'].value_counts().to_dict()
}

print(summary)
print("Examples of discrepant groups (up to 10):")
print(dbil_diff.head(10).to_string(index=False))

{'real_groups_with_DBIL': 109, 'gen_groups_eligible': 109, 'hard_na_or_missing': 0, 'by_reason': {}}
Examples of discrepant groups (up to 10):
Empty DataFrame
Columns: [compound, time, dose, valid_n_real, valid_n_gen, gen_group_size, reason]
Index: []

In [99]:
feat = "DBIL(mg/dL)"
zcol = f"{feat}_z"
sus = results_df.query(
    "(compound == 'carboplatin' and time == '29 day' and dose == 'High') or "
    "(compound == 'iproniazid' and time == '29 day' and dose == 'High')"
)
cols_to_show = [c for c in [ 'compound','time','dose', feat, zcol, 'vehicle','Vehicle','lab','Lab'] if c in sus.columns]
print(sus[cols_to_show])

        compound    time  dose  DBIL(mg/dL)_z
118  carboplatin  29 day  High       6.260990
119  carboplatin  29 day  High      -0.447214
120  carboplatin  29 day  High      -0.447214
121  carboplatin  29 day  High      10.733126
122  carboplatin  29 day  High      -0.447214
310   iproniazid  29 day  High      -0.447214
311   iproniazid  29 day  High       4.024922
312   iproniazid  29 day  High      -0.447214
313   iproniazid  29 day  High      -0.447214
314   iproniazid  29 day  High      -0.447214

In [100]:
#confusion_df.to_csv('/account001/mansi.chandra/clin_path/results_plots_updated/contrastive_high_threshold.csv', index=False)

In [101]:
gen['COMPOUND_NAME'].unique()

array(['amiodarone', 'amitriptyline', 'amphotericin B', 'benzbromarone',
       'benziodarone', 'bromobenzene', 'carboplatin', 'cephalothin',
       'chlormadinone', 'chlorpromazine', 'cisplatin', 'cyclosporine A',
       'diltiazem', 'enalapril', 'gemfibrozil', 'imipramine',
       'iproniazid', 'ketoconazole', 'lomustine', 'lornoxicam',
       'mefenamic acid', 'meloxicam', 'phenobarbital', 'promethazine',
       'rosiglitazone maleate', 'thioacetamide', 'thioridazine',
       'triazolam'], dtype=object)

In [102]:
real[(real['COMPOUND_NAME'] == 'cyclosporine A')&(real['DOSE_LEVEL'] == 'Control') & (real['SACRIFICE_PERIOD'] == '4 day')].iloc[:, 11:]

,ALP(IU/L),TC(mg/dL),TG(mg/dL),PL(mg/dL),TBIL(mg/dL),DBIL(mg/dL),GLC(mg/dL),BUN(mg/dL),CRE(mg/dL),Na(meq/L),...,Plat(x10_4/uL),WBC(x10_2/uL),Neu(%),Eos(%),Bas(%),Mono(%),Lym(%),PT(s),APTT(s),Fbg(mg/dL)
477,1509,64,59.0,121,0.01,0.0,187,14.0,0.1,140.0,...,131.4,90.9,12.0,0.0,0.0,2.0,85.0,16.9,21.6,268.0
478,1809,85,75.0,149,0.00,0.0,204,15.0,0.2,142.0,...,112.8,92.4,17.0,1.0,0.0,3.0,79.0,16.4,21.7,309.0
479,2005,91,207.0,180,0.00,0.0,227,20.0,0.1,139.0,...,121.8,92.8,12.0,1.0,0.0,2.0,85.0,16.6,20.8,332.0
480,1646,64,69.0,117,0.00,0.0,207,15.0,0.2,142.0,...,113.9,85.9,8.0,1.0,0.0,2.0,88.0,17.2,22.8,297.0
481,2055,86,116.0,157,0.00,0.0,185,17.0,0.2,143.0,...,133.0,78.8,10.0,1.0,0.0,3.0,85.0,15.7,23.4,302.0

In [103]:
gen[(gen['COMPOUND_NAME'] == 'cyclosporine A')&(gen['DOSE_LEVEL'] == 'High') & (gen['targetTime'] == '4 day')].iloc[:, 18:]

,ALP(IU/L),TC(mg/dL),TG(mg/dL),PL(mg/dL),TBIL(mg/dL),DBIL(mg/dL),GLC(mg/dL),BUN(mg/dL),CRE(mg/dL),Na(meq/L),...,Plat(x10_4/uL),WBC(x10_2/uL),Neu(%),Eos(%),Bas(%),Mono(%),Lym(%),PT(s),APTT(s),Fbg(mg/dL)
3425,1544,77.381510,89.677734,141.33757,0.01,0.00,193.99867,17,0.2,141.6,...,128.708680,90.336630,15.049395,0.884547,0.131549,2.312721,80.505950,16.099705,21.935854,296.67440
3426,1469,71.159810,83.803950,139.26476,0.01,0.01,195.48193,16,0.2,142.2,...,124.149080,89.635990,14.555665,0.886614,0.188428,2.274700,81.363590,16.414629,22.473250,298.58750
3427,1506,78.384090,88.470245,144.52496,0.01,0.02,193.33203,16,0.2,142.0,...,129.027440,90.410540,16.774221,0.978344,0.054607,2.457310,78.502144,16.229320,22.277815,297.62350
3428,1487,75.791450,70.535675,138.87862,0.01,0.00,192.34258,17,0.2,142.8,...,123.664520,91.843544,13.857878,0.932198,0.019681,2.548171,81.883575,16.158663,22.632570,298.58150
3429,1532,72.749760,88.026825,141.40538,0.01,0.01,195.75485,16,0.2,142.4,...,134.471620,107.207130,15.816009,0.918457,0.098989,2.634734,79.650080,16.178950,22.116697,302.39523
3430,1542,76.102490,83.600200,141.31421,0.01,0.01,194.03072,16,0.2,141.7,...,129.776290,82.700010,15.372733,0.865611,0.188301,2.262291,80.236300,16.184443,22.021038,297.63828
3431,1448,72.751170,79.466430,138.61674,0.01,0.00,195.81921,16,0.2,142.2,...,129.586670,99.013824,14.454117,0.877895,0.014480,2.306740,81.379920,16.450110,22.378790,298.54388
3432,1523,82.686790,83.828210,145.60368,0.01,0.01,192.06044,16,0.2,142.1,...,120.656380,82.939964,16.568802,0.970313,0.250399,2.594272,78.528310,16.238420,21.841380,298.66537
3433,1457,75.720505,69.648415,139.93205,0.01,0.02,191.98914,17,0.3,142.7,...,116.661240,85.317410,13.690993,0.935566,0.035346,2.683551,81.870160,16.167320,22.335000,298.43723
3434,1516,68.868240,82.323300,134.56119,0.01,0.02,196.27864,16,0.2,142.5,...,126.180500,105.810380,15.839043,0.932768,0.104482,2.601346,79.707600,16.246075,22.102959,301.18567
3435,1533,76.993645,81.936440,140.74050,0.01,0.00,194.39078,16,0.2,141.7,...,136.001370,79.105810,15.283019,0.872951,0.051082,2.300303,80.290410,16.206577,21.957556,297.03638
3436,1445,71.153100,77.238976,137.28683,0.01,0.01,196.59357,16,0.2,142.2,...,117.912544,85.862400,14.551414,0.882941,0.036070,2.301807,81.300865,16.471027,22.422693,297.34990
3437,1535,81.449050,82.899160,142.97950,0.01,0.01,192.93803,16,0.2,142.1,...,127.988106,96.233210,16.630352,0.975855,0.032082,2.599968,78.485160,16.241007,21.895670,298.04750
3438,1468,74.509770,69.666700,140.46729,0.01,0.00,192.85562,17,0.2,142.7,...,124.384110,91.442930,13.852609,0.934124,0.000589,2.591759,81.780716,16.174866,22.435543,298.47473
3439,1525,70.051765,83.177260,133.66210,0.01,0.01,196.35823,16,0.2,142.4,...,126.803100,100.646020,15.706391,0.934712,0.002600,2.673128,79.755840,16.244610,22.034166,302.09930
3440,1539,77.132260,84.443520,141.22113,0.01,0.00,194.55981,16,0.2,141.7,...,127.739410,82.741490,15.339903,0.869772,0.175410,2.237690,80.320920,16.204650,22.066229,297.23975
3441,1449,71.825720,79.479580,138.78270,0.01,0.00,195.91449,16,0.2,142.2,...,114.484920,82.721330,14.465578,0.876768,0.036139,2.272489,81.420380,16.472970,22.403915,298.23953
3442,1520,87.226006,84.828360,143.71404,0.01,0.00,192.95164,16,0.2,142.1,...,127.273346,93.129570,16.574255,0.968381,0.141474,2.513730,78.647970,16.241953,22.011503,298.37253
3443,1463,76.385185,69.949950,141.03156,0.01,0.01,192.29290,17,0.2,142.8,...,117.039750,91.871110,13.894168,0.934404,0.029576,2.585491,81.775580,16.190060,22.442602,298.73926
3444,1526,70.982376,82.929830,134.38805,0.01,0.00,196.34598,16,0.2,142.5,...,126.099660,102.556305,15.851182,0.931504,0.035627,2.558799,79.749650,16.253681,22.133501,301.90936
3445,1553,74.095320,88.339226,141.06543,0.01,0.01,194.24713,17,0.2,141.7,...,121.597500,90.999954,15.094021,0.878282,0.150074,2.270196,80.528280,16.131594,22.003590,297.40747
3446,1474,71.052850,84.182014,139.02325,0.00,0.01,196.18790,16,0.2,142.2,...,123.205860,90.746216,14.551661,0.885681,0.273494,2.244552,81.420810,16.432957,22.508965,299.05185
3447,1522,80.242450,87.291756,144.26315,0.01,0.00,193.57400,16,0.2,142.0,...,126.997640,92.437770,16.745438,0.971015,0.006343,2.463157,78.550010,16.238905,22.227030,298.16647
3448,1486,75.072930,72.766270,138.74226,0.01,0.02,193.26110,17,0.3,142.7,...,120.147270,94.988420,13.884484,0.933459,0.029122,2.471326,81.926605,16.170734,22.724100,299.41415
3449,1527,71.763810,85.832330,137.74593,0.01,0.02,195.62515,16,0.3,142.5,...,130.896000,106.416466,15.728731,0.916473,0.022626,2.684503,79.704730,16.183910,22.049103,301.35165